---
- hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco
      transport: cli

  tasks:
    - name: configure baseline
      ios_config:
        lines: 
          - ip address {{ hostvars[inventory_hostname].loopback }} 255.255.255.255
        parents:
          - "interface lo0"



    