---
- name: Get Interface info
  hosts: all
  gather_facts: false

  tasks:
    - name: show interface
      raw: "show ip interface brief"

      register: print_output
    - debug: var=print_output.stdout_lines