---
- name: Get Interface info
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run show version on remote devices
      ios_command:
        commands: 
          - show version


      register: print_output
    - debug: var=print_output.stdout_lines
    - name: Save output to a file
      copy: content="{{print_output.stdout_lines[0]}}" dest="./output/{{inventory_hostname}}.txt"